<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML and DL</b></center>

<center><b><h1>Lab - 6</b></center>    
<pre>    

# Decision Tree Classifier

In [7]:
from sklearn.datasets import load_iris 

# Import iris data ser using sklearn

In [9]:
data = load_iris()

In [11]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [19]:
data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

# Importing the libraries

In [31]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import tree

# Divide the data into input and output

In [21]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [28]:
data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

# Splitting the dataset into the Training set and Test set

In [33]:
x = data['data']


In [35]:
y = data['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Fitting DecisionTreeClassifier   on dataset

In [94]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)

In [96]:
print(f"Final shape of Training Data: {x_train.shape}")
print(F"final test of traing data :: {x_test.shape}")
print(f"Final shape of Training Data: {y_train.shape}")
print(F"final test of traing data :: {y_test.shape}")

Final shape of Training Data: (105, 4)
final test of traing data :: (45, 4)
Final shape of Training Data: (105,)
final test of traing data :: (45,)


In [99]:
model = DecisionTreeClassifier(splitter="random")

In [101]:
model.fit(x_train,y_train)

DecisionTreeClassifier(splitter='random')

# Display Decision Tree

In [104]:
from sklearn import tree

In [106]:
%matplotlib qt

In [108]:
tree.plot_tree(model)

[Text(0.3, 0.9444444444444444, 'x[2] <= 1.726\ngini = 0.663\nsamples = 105\nvalue = [30, 39, 36]'),
 Text(0.23333333333333334, 0.8333333333333334, 'gini = 0.0\nsamples = 28\nvalue = [28, 0, 0]'),
 Text(0.26666666666666666, 0.8888888888888888, 'True  '),
 Text(0.36666666666666664, 0.8333333333333334, 'x[2] <= 4.54\ngini = 0.524\nsamples = 77\nvalue = [2.0, 39.0, 36.0]'),
 Text(0.3333333333333333, 0.8888888888888888, '  False'),
 Text(0.13333333333333333, 0.7222222222222222, 'x[2] <= 1.955\ngini = 0.174\nsamples = 32\nvalue = [2, 29, 1]'),
 Text(0.06666666666666667, 0.6111111111111112, 'gini = 0.0\nsamples = 2\nvalue = [2, 0, 0]'),
 Text(0.2, 0.6111111111111112, 'x[3] <= 1.356\ngini = 0.064\nsamples = 30\nvalue = [0, 29, 1]'),
 Text(0.13333333333333333, 0.5, 'gini = 0.0\nsamples = 23\nvalue = [0, 23, 0]'),
 Text(0.26666666666666666, 0.5, 'x[1] <= 2.858\ngini = 0.245\nsamples = 7\nvalue = [0, 6, 1]'),
 Text(0.2, 0.3888888888888889, 'x[1] <= 2.221\ngini = 0.5\nsamples = 2\nvalue = [0, 1, 1

# Predict the x_test 

In [113]:
model.score(x_train,y_train)

1.0

In [115]:
model.score(x_test,y_test)

0.9555555555555556

# Import diabetes.csv dataset 

In [117]:
df = pd.read_csv('diabetes.csv')

In [119]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age       Outcome  
0                       0.627   50      Diabetic  
1                       0.351   31  Non Diabetic  
2                       0.672   32      Diabetic  
3                       0.167   21  Non Diabetic  
4                       2.288   33      Diabetic  
..                        ...  ...           ...  
763                     0.171   63  Non Diabetic  
764                     0.340   27  Non Diabetic  
765                     0.245   30  Non Diabetic  
766                     0.349   47      Diabetic  
767                     0.315   23  Non Diabetic  

[768 rows x 9 columns]

# Check the distribution of the target

In [123]:
print(df['Outcome'].value_counts())

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64


# Replace zeros with NaN for specific columns

In [126]:
columns_to_replace = ['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
df[columns_to_replace] = df[columns_to_replace].replace(0,np.nan)

# Check for missing values

In [134]:
print(df.isnull().sum())

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64


# Fill missing values with median

In [137]:
for col in columns_to_replace:
    df[col] = df[col].fillna(df[col].mean())

In [139]:
print(df.isnull().sum())

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64


# Visualize Distributions

In [154]:
sns.pairplot(df,hue='Outcome')

In [156]:
sns.heatmap(df.corr(),annot=True,cmap='coolwarm')
plt.plot()

[]

# Convert Targer data into interger code

In [146]:
df['Outcome'] = df['Outcome'].map({"Diabetic":1,"Non Diabetic" : 0 })

In [150]:
plt.plot()

[]

# Divide the data into input and output

In [162]:
x = df.iloc[::,:-1:]

In [164]:
y =  df['Outcome']

# Splitting the dataset into the Training set and Test set

In [297]:
x_train,x_test,y_train,y_test  = train_test_split(x,y,random_state=42,test_size=0.3)

In [299]:
print(f"Final shape of Training Data: {x_train.shape}")
print(F"final test of traing data :: {x_test.shape}")
print(f"Final shape of Training Data: {y_train.shape}")
print(F"final test of traing data :: {y_test.shape}")

Final shape of Training Data: (537, 8)
final test of traing data :: (231, 8)
Final shape of Training Data: (537,)
final test of traing data :: (231,)


# Create Model

In [302]:
model =  DecisionTreeClassifier(splitter='random')

In [304]:
model.fit(x_train,y_train)

DecisionTreeClassifier(splitter='random')

In [306]:
model.score(x_train,y_train)

1.0

In [308]:
model.score(x_test,y_test)

0.6796536796536796

# Fitting DecisionTreeClassifier   on dataset

# Display Decision Tree

In [221]:
from sklearn import tree
%matplotlib qt
tree.plot_tree(model)

[Text(0.4592181467181467, 0.9705882352941176, 'x[1] <= 112.353\ngini = 0.455\nsamples = 537\nvalue = [349, 188]'),
 Text(0.22695463320463322, 0.9117647058823529, 'x[4] <= 173.0\ngini = 0.229\nsamples = 227\nvalue = [197, 30]'),
 Text(0.34308638996138996, 0.9411764705882353, 'True  '),
 Text(0.12186293436293437, 0.8529411764705882, 'x[4] <= 121.477\ngini = 0.206\nsamples = 215\nvalue = [190, 25]'),
 Text(0.05791505791505792, 0.7941176470588235, 'x[0] <= 3.359\ngini = 0.087\nsamples = 88\nvalue = [84, 4]'),
 Text(0.03088803088803089, 0.7352941176470589, 'x[2] <= 38.804\ngini = 0.056\nsamples = 70\nvalue = [68, 2]'),
 Text(0.015444015444015444, 0.6764705882352942, 'x[5] <= 54.1\ngini = 0.375\nsamples = 4\nvalue = [3, 1]'),
 Text(0.007722007722007722, 0.6176470588235294, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.023166023166023165, 0.6176470588235294, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.04633204633204633, 0.6764705882352942, 'x[0] <= 2.938\ngini = 0.03\nsamples = 

# Predict the x_test 

In [310]:
y_predict = model.predict(x_test)

# Display Training Accuracy

In [316]:
model.score(x_train,y_train)

1.0

# Display Test Accuracy

In [318]:
model.score(x_test,y_test)

0.6796536796536796

# Confusion Matrix

In [320]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [322]:
cm = confusion_matrix(y_test,y_predict,)
cm

array([[109,  42],
       [ 32,  48]], dtype=int64)

# Save Model State

In [361]:
import pickle

In [363]:
with open('model.pkl','wb') as file:
    pickle.dump(model,file)

# Load Model from Disk

In [366]:
with open('model.pkl','rb') as file:
    loaded_model = pickle.load(file)

In [368]:
loaded_model.predict(x_test)

array([1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0], dtype=int64)

In [370]:
from sklearn.metrics import classification_report

In [372]:
print(classification_report(y_predict,y_test))

              precision    recall  f1-score   support

           0       0.72      0.77      0.75       141
           1       0.60      0.53      0.56        90

    accuracy                           0.68       231
   macro avg       0.66      0.65      0.66       231
weighted avg       0.67      0.68      0.68       231

